I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 12, in script
    e eduardo normal "Nothing's perfect, the world's not perfect, but it's there for us, trying the best it can. That's what makes it so damn beautiful."
Exception: Say has image attributes ('eduardo', 'normal'), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 12, in script
    e eduardo normal "Nothing's perfect, the world's not perfect, but it's there for us, trying the best it can. That's what makes it so damn beautiful."
  File "/home/p1zza/Apps/renpy-8.0.3-sdk/renpy/ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/home/p1zza/Apps/renpy-8.0.3-sdk/renpy/exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "/home/p1zza/Apps/renpy-8.0.3-sdk/renpy/character.py", line 1206, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "/home/p1zza/Apps/renpy-8.0.3-sdk/renpy/character.py", line 1030, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "/home/p1zza/Apps/renpy-8.0.3-sdk/renpy/character.py", line 956, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('eduardo', 'normal'), but there's no image tag associated with the speaking character.

Linux-5.15.0-60-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.0.3.22090809
visualnovel 1.0
Mon Feb 20 15:05:03 2023
